# Generated by Django 4.1.7 on 2023-03-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_success',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
