# Generated by Django 4.1.7 on 2023-03-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paymentType',
            field=models.CharField(choices=[('PC', 'PC'), ('AC', 'AC')], default='PC', max_length=2),
            preserve_default=False,
        ),
    ]
