# Generated by Django 4.1.7 on 2023-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_avatar_user_city_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aa',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
