# Generated by Django 4.1.7 on 2023-02-17 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_aa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aa',
        ),
    ]
