# Generated by Django 4.1.7 on 2023-02-21 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('preview', models.ImageField(null=True, upload_to='lessons/previews')),
                ('video_link', models.URLField(max_length=255, null=True)),
                ('course', models.ManyToManyField(blank=True, null=True, related_name='lessons', to='courses.course')),
            ],
        ),
    ]
