# Generated by Django 4.1.7 on 2023-02-17 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_preview'),
        ('lessons', '0002_alter_lesson_preview_alter_lesson_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course'),
            preserve_default=False,
        ),
    ]
