# Generated by Django 4.1.7 on 2023-02-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_preview'),
        ('lessons', '0004_remove_lesson_course_lesson_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ManyToManyField(null=True, related_name='lessons', to='courses.course'),
        ),
    ]
